apiVersion: v1
data:
  mapRoles: ' | 
  - groups: - system:masters rolearn: arn:aws:iam:: arn:aws:iam::419763087940:role/UdacityFlaskDeployCBKubectlRole
    username: build
  - groups: - system:masters rolearn: arn:aws:iam::419763087940:role/UdacityFlaskDeployCBKubectlRole
    username: build 
  - groups: - system:bootstrappers - system:nodes rolearn: arn:aws:iam::419763087940:role/eksctl-fabulous-rainbow-163254533-NodeInstanceRole-15D7APVR43GDB
    username: system:node:{{EC2PrivateDNSName}}'
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-25T05:09:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "122641"
  uid: bfabec01-2c5b-49f9-b962-f0452a9c486f
