apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::419763087940:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-O0Y9PU16445C
      username: system:node:{{EC2PrivateDNSName}}
      - groups:
      - system:masters
      rolearn: arn:aws:iam::419763087940:role/UdacityFlaskDeployCBKubectlRole
      username: build
      mapUsers: |
                  []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-26T22:55:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1902"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2e7c1d5e-7942-4232-8536-50e8d929c5d6
